# Generated by Django 4.0.3 on 2022-03-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Event',
        ),
    ]
